"""Issue #419: generate the committed v100 unchanged-mesh fixtures ONCE.

Runs the Blender EXACT boolean solver (the only reliable backend in the
project venv) in a single process so the four STLs share one triangulation
context. The four files prove the position-sensitive legs of the check
with NO trimesh boolean at test time:

  v100-plate.stl          – plain 120×80×6 plate (the parent baseline)
  v100-plate-recut.stl    – same plate, a 38 mm bore at the centre: a
                             genuine edit (face count and volume both
                             move well beyond the 0.1% / 1% epsilon)
  v100-plate-hole-A.stl   – same plate, a 38 mm bore at (0, 0)
  v100-plate-hole-B.stl   – same plate, a 38 mm bore at (10, 10)
                             (a position move of the same hole: same
                              volume within 0.0002 mm³, same face count,
                              same bbox — only the centroid moves ≈1.34 mm:
                              the "move the hole" false-fail PM flagged)

The hole pair (A/B) is generated by the same 100-section cylinder at two
positions, so the ONLY metric that separates them is the volume centroid
(`mesh.center_mass`) — the position-sensitive leg of the fix.
"""

from __future__ import annotations

from pathlib import Path

import trimesh
from trimesh.creation import box, cylinder

FIXTURES_DIR = Path(__file__).parent.parent / "tests" / "fixtures" / "stl"

PLATE = (120.0, 80.0, 6.0)
BORE_RADIUS_MM = 19.0  # d = 38 mm
BORE_HEIGHT_MM = 60.0  # well beyond the 6 mm plate — clean bore
BORE_SECTIONS = 100


def _plate() -> "trimesh.Trimesh":
    return box(PLATE, center=True)


def _plate_with_bore(cx: float, cy: float) -> "trimesh.Trimesh":
    p = _plate()
    h = cylinder(
        radius=BORE_RADIUS_MM,
        height=BORE_HEIGHT_MM,
        sections=BORE_SECTIONS,
    )
    h.apply_translation([cx, cy, 0.0])
    return trimesh.boolean.difference([p, h])


def main() -> None:
    FIXTURES_DIR.mkdir(parents=True, exist_ok=True)
    meshes = {
        "v100-plate.stl": _plate(),
        "v100-plate-recut.stl": _plate_with_bore(0.0, 0.0),
        "v100-plate-hole-A.stl": _plate_with_bore(0.0, 0.0),
        "v100-plate-hole-B.stl": _plate_with_bore(10.0, 10.0),
    }
    for name, mesh in meshes.items():
        path = FIXTURES_DIR / name
        mesh.export(str(path))
        print(
            f"{name}: faces={len(mesh.faces)} "
            f"vol={mesh.volume:.4f} mm3 "
            f"cm={[round(float(x), 6) for x in mesh.center_mass]} "
            f"bounds={mesh.bounds.tolist()}"
        )


if __name__ == "__main__":
    main()
